version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /packages/data-python
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
